### ISSUE TITLE
better suggestions

### ISSUE THREAD

**Issue by DILPREET1910** [notion-enhancer/repo#122]
is there a way you can create an extension that suggests 

- grammatical errors
- better formation of sentences 
- spelling errors 
- better alternative words for words that are repeated multiple times in a sentence 

just like gmail and grammarly does.
or do I have to use gmail's draft box and then copy paste the text?

**Comment by ncoquelet** [comment]
Hi
If you use notion in a browser, there are already many browser extensions that help you write better text.
Example for chromium browser https://chrome.google.com/webstore/search/gramatical%20languagetool?hl=en&_category=extensions

**Comment by dragonwocky** [comment]
In-browser, LanguageTool/Grammarly/related extensions can probably do this for you. Otherwise, Notion AI might be able to help you out with your writing. At this stage, though, this feature is out of scope for the notion-enhancer. I may come back to it one day, but for now I'm closing this issue as not planned, sorry.
