### ISSUE TITLE
Capability to password protected a page

### ISSUE THREAD

**Issue by iamsmkr** [notion-enhancer/repo#130]
BEFORE MAKING A FEATURE REQUEST, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

FEATURE REQUESTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What makes the feature necessary?**
Password protecting a page is essential if notion wishes to encourage people to use notion for sensitive information. We all share our laptops with our family and friends once in a while and may not want them to have access to sensitive information.

**How would the feature work?**
Just like we can lock a page, notion could provide a dropdown option to password protect a page.

**Comment by dragonwocky** [comment]
The notion-enhancer runs after a Notion page has loaded, so any password protection that could be done would be superficial at best and easy to circumvent and could mess pretty seriously with your Notion content at worst - my initial testing of password protection last time this feature was requested ended with me losing a significant amount of work.

If you would like to prevent your family and friends from accessing Notion, consider logging out before giving them your device. Even better, if information is sensitive enough to require password protection (e.g. banking details or other passwords), you probably should be using something like 1Password, Bitwarden, Standard Notes, or another password protected vault of some sort to store that information instead of Notion.
